#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/svahost/rustdesk /usr/bin/svahost

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/svahost.service ]; then
			rm /etc/systemd/system/svahost.service /usr/lib/systemd/system/svahost.service /usr/lib/systemd/user/svahost.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/svahost/files/systemd/svahost.service /usr/lib/systemd/system/svahost.service
		# try fix error in Ubuntu 18.04
		# Failed to reload svahost.service: Unit svahost.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/svahost.service:10: Executable path is not absolute: pkill -f "rustdesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/svahost.service
		fi
		systemctl daemon-reload
		systemctl enable svahost
		systemctl start svahost
	fi
fi
